### ISSUE TITLE
Remix themes

### ISSUE THREAD

**Issue by benkaiser** [Neutron-Creative/Singlelink#177]
Is there a way to make a marketplace theme show up under "Your themes" in the Appearance tab?

Would be nice to start from a marketplace theme and just tweak a few values from there.

Open to submitting a PR!

**Comment by benkaiser** [comment]
Guessing #147 might be the same intention?

**Comment by jimmybisenius** [comment]
Taking a look into this!

**Comment by jimmybisenius** [comment]
I'm going to close this as we get rid of themes temporarily in v4, but this is worth having a discussion again soon and reopening once they are re-added shortly!

**Comment by benkaiser** [comment]
One question  here @jimmybisenius, if it's being removed, is that just from a dev version? or are you deploying a v4 to the public service without themes? (i.e. will my theme drop from [my singlelink](https://app.singlelink.co/u/benkaiser))

**Comment by jimmybisenius** [comment]
Rest assured that none of our hosted users will be affected yet!
Fundamentally, we're changing this repository from a "micro-site platform" (SaaS like service that allows users to signup and create pages) to strictly a self-hosted linktree alternative.

The original platform still exists, it's code is just being moved elsewhere since it seems most users would rather self-host with something much simpler like I've built with v4.
