### ISSUE TITLE
Can't delete profile

### ISSUE THREAD

**Issue by AnimeshRy** [Neutron-Creative/Singlelink#54]
The option to delete profile doesn't work. Clicking on it just loads the website but does nothing, even after reloading and trying multiple times, the delete profile option does not work. 

![Singlelink - A free   open-source Linktree alternative - Brave 27-10-2020 17_39_54](https://user-images.githubusercontent.com/54435702/97299735-74874c00-187b-11eb-811e-9d5315b8aa60.png)

Nothing happens after this.

**Comment by jimmybisenius** [comment]
Hey @AnimeshRy , unfortunately I'm unable to replicate this issue locally.

Would you be able to send us over a screenshot of your console and let us know what browser and environment you're using so we can try and reproduce this issue with your configuration?

**Comment by AnimeshRy** [comment]
Sure, I'm using 
- 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)
- Windows 10 OS Version 1909 (Build 18363.1139)
- Flash - (Disabled)
- V8 8.6.395.17

This also happened with the Microsoft Edge browser. By looking at the console, it looks like the POST request fails somehow.

![Singlelink - A free   open-source Linktree alternative - Brave 28-10-2020 14_18_37](https://user-images.githubusercontent.com/54435702/97413683-1618a700-1929-11eb-853b-9db8c02126a4.png)

**Comment by jimmybisenius** [comment]
Alrighty, I looked into this for you.
Currently, our delete function is hardcoded so that it will throw a 400 request if you try to delete the only profile on the account, which from the looks of it is happening here.
You should be able to confirm this is the case by creating an additional profile, and then attempting to delete it.

I'll report this as a bug regardless, there definitely should be better communication with the user about what's going on/why it fails.

Thanks again!
