### ISSUE TITLE
Password and Hash revealed in the console. 

### ISSUE THREAD

**Issue by AnimeshRy** [Neutron-Creative/Singlelink#56]
There are too many logs inside the console as the dashboard loads. On top of that looks like the user information is also logged inside the console. I can't clearly say if the hashed passwords can be cracked but they are available openly.

[removed for privacy]

**Comment by NavidK0** [comment]
This should be resolved now (ccbbf4e047e742beefce4f33e8e626af5c3a64ef). Please let us know if you find more. We will be working to control the amount of data being sent from the server with the upcoming refactor as well.

**Comment by AnimeshRy** [comment]
Nope, refreshing the dashboard page still logs these in the console.

**Comment by jimmybisenius** [comment]
Hey @AnimeshRy , I can assure you this information is only open and accessible to a user after logging in and having their JWT verified by the server, meaning your password is safe (if you'd like, you can sort through the source code to verify this).

Regarding the bug fix, you should see the changes in the beta ([beta-app.singlelink.co](https://beta-app.singlelink.co)), rather than the production version that you're using ([app.singlelink.co](https://app.singlelink.co)), as we don't directly roll any changes to production anymore (rather, we test them extensively with a private beta audience, then public, before pushing the updates live for everyone).

We appreciate the bug report, we're doing our best to build a product & community you can be proud to be a part of!
