### ISSUE TITLE
Running Locally

### ISSUE THREAD

**Issue by DanielLvovsky** [Neutron-Creative/Singlelink#59]
Hi there,

I recently found this project and I was interesting in looking at more closely. My main issue is to running it locally. Is there any step by step way on how to do it since the readme isn't that descriptive.
 
Thanks,
Daniel

**Comment by DanielLvovsky** [comment]
Ok so I figured out how to run the client side locally. Can anyone here guide me on how to setup the database. And can I use services like heroku or do I need to use DigitalOcean specifically?

Any help is appreciated

Thanks,
Daniel

**Comment by jimmybisenius** [comment]
Hey @DanielLvovsky ! Sorry to get back to you a bit late, it's been a crazy weekend here at Singlelink!

Running Singlelink locally is a bit tricky right now, which is why we're hard at work getting an easy-to-use Docker image setup and working for our next milestone (v2.1, currently v2.0.1).

If you want to give it a go beforehand, I've posted the steps below.

**Pre-requisites:** two NodeJS servers (one for client, one for API), and a MongoDB server.
If you don't have servers already, we highly recommend our partners at DigitalOcean for this.

**Installation**
1. Clone https://github.com/Neutron-Creative/Singlelink onto both NodeJS servers (one for the client, one for the api)
2. Download the required dependencies via npm install and apt update/install
3. Fill out the config-example.js file on your API server, and then rename it to config.js (this is where you'll put the database information, client & API urls, etc.)
4. Set the $BASE_URL environment variable on your client to the API url of the other server
5. Install pm2 on both servers
6. run the following command on your API server
> cd server/ && pm2 start index.js
7. Run the following command on your client server
> nuxt-start --port 80 --hostname <your-domain-here>
8. You're good to go!

Let me know if you have any issues, I know the documentation is a bit outdated but this is another large task we plan on working on ASAP.

Hope this helps! 🤠👍
Jimmy Bisenius
Founder & President of Neutron Creative, Maintainer @ Singlelink
