### ISSUE TITLE
Custom domain support

### ISSUE THREAD

**Issue by jimmybisenius** [Neutron-Creative/Singlelink#6]

**Comment by NavidK0** [comment]
Needs testing on a live server.

**Comment by NavidK0** [comment]
Latest update in future-release branch removes support for custom domains again. This is because the functionality has been moved to an external proxy for better modularity (and proper scalable SSL support). Because the proxy work has not been completed yet, the custom domain functionality has been temporarily made unfunctional.

**Comment by jimmybisenius** [comment]
Resolved in commit 09dd044cbfb0b08547d3e0cd46e898a1d9a8c2dc.

Let's Encrypt SSL Custodian still not complete, move to separate issue.
